"""
Django settings for ProjetInfoCIR3 project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import hashlib
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
DEEP_AI_API_KEY = "0996e48b-cbbb-4403-9ce6-5be3337ebda7"
OPENAI_API_KEY = "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"
APIKEY2 = "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"
APIKEY3 = "c2stcHJvai01T20yc1hoUV9TV3U2MkZWVURrU2k3QnZBZE9Uakg3bWc2U0RScjRuaGw4cVJFWVM4aFhRVHk1UGNjeDZVNnBqR2gwUDM3UkE3WlQzQmxia0ZKQ3F0OS1xYTN4WENaaHBxMXNPRmhycDBEQ2NfcUFLMzdxYWlsRC1fdVY1Z2psWXV6dThfLTloQVFVMVd1OTBhSjJ4YnFNVl9ma0E="
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ydfo#((_$&f%15!w0hzs3q54opsad_^_qwo7w-z0=ent6*kjn8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# CUSTOM VARIABLES

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/login/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Ensures existing loggers are not disabled
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # Default Django logger (set to WARNING or higher to suppress DEBUG logs)
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Your application logs
        'home': {  # Replace with the name of your app
            'handlers': ['console'], 
            'level': 'DEBUG',  # Log only messages from your app
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',  # Suppress other non-critical logs
    },
}

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"   # Directory where collectstatic will place all files

"""
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Chemin vers le dossier static
]
"""

# END OF CUSTOM VARIABLES


# Application definition

INSTALLED_APPS = [
    'login',
    'home',
    'register',
    'telemetry',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'testAPI',
    'ChatBotAI',
    'corsheaders',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    #'http://<IP_ADRESSE_DE_L_AUTRE_PC>:8000',  # Remplacez avec l'adresse IP
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'telemetry.middleware.TelemetryMiddleware',  # Add this line to include the custom middleware
    'corsheaders.middleware.CorsMiddleware',
]

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'http://localhost',
    #'http://<IP_ADRESSE_DE_L_AUTRE_PC>:8000',  # Remplacez avec l'adresse IP de l'autre PC
    #'http://<NOM_DE_DOMAINE>',                # Si un nom de domaine est utilisé
]

CSRF_COOKIE_SECURE = False  # Mettez sur True si vous utilisez HTTPS
CSRF_COOKIE_HTTPONLY = False  # Assurez-vous qu'il peut être lu par JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'  # Ou 'Strict' selon vos besoins

ROOT_URLCONF = 'ProjetInfoCIR3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Ensure this line includes your templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjetInfoCIR3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
